application: pyperugia
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: templates/css

- url: /images
  static_dir: templates/images

- url: /favicon.ico
  static_files: templates/images/favicon.ico
  upload: templates/images/favicon.ico

- url: .*
  script: main.py
